### ISSUE TITLE
the "Get-file-path-Extension" is fabulous

### ISSUE THREAD

**Issue by stefanibus** [Riuujin/get-file-path-chrome-extension#1]
this extension seems to be the only extension of its kind!

this extension speeds up the time it takes to jump back from  localhost-pages to the relevant local documents on your Hard-drive. The addOn is especially helpful for developers who browse through various sub-projects on localhost simultaniously , and edit various pages at the same time. I love the extension - it is offering a fabulous service. 
 
https://chrome.google.com/webstore/detail/get-file-path/ggoohhjefaikbncimfcekpbhgggdnidc

REMARK: 
I happened to have set up my first rule mistakenly, which resulted in that new button nowhere to be found! It took me more than 10 Minutes to get this established, after I had installed your extension.   I created my second rule only much later, this time: correctly:  I think your example text should be more specific:  

Name: 'localhost'
Url: 'https://www.localhost/yourPath/'
Directory: 'c:\yourPath\aaa\bbb'

Any you should mention where to find the new button and when that button will not be visible. 

 It is great to easily jump to the specified files on my filesystem with ease // I can now just copy the desired file path to  clipboard   and paste it back into sublime - I was looking for exactly this service for a long time. I think this is fabulous.   This is not an Issue or a ticket, but just some feedback and a suggestion to better explain where the trigger for the copy/paste-process should be expected, once the add-on is implemented.

**Comment by Riuujin** [comment]
> Any you should mention where to find the new button and when that button will not be visible.

Stange the new button should always be visible, I will see if I can reproduce this.

As for the example text I think I will indeed change it to be more specific.
